-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 07:51:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda de Produto` DEFAULT CHARACTER SET utf8 ;
USE `venda de Produto` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `dscategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`Produtos` (
  `idProduto` INT NOT NULL,
  `dsPRoduto` VARCHAR(45) NOT NULL,
  `preco Float` FLOAT NOT NULL,
  `qtdade` INT NOT NULL,
  `foto` LONGBLOB NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  -- INDEX `fk_Produtos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda de Produto`.`CLiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`CLiente` (
  `idCLiente` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCLiente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`Pedidos` (
  `idPedidos` INT NOT NULL,
  `date` DATE NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Sessao` VARCHAR(45) NOT NULL,
  `CLiente_idCLiente` INT NOT NULL,
  PRIMARY KEY (`idPedidos`),
  -- INDEX `fk_Pedidos_CLiente_idx` (`CLiente_idCLiente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_CLiente`
    FOREIGN KEY (`CLiente_idCLiente`)
    REFERENCES `venda de Produto`.`CLiente` (`idCLiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda de Produto`.`Pedidoitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`Pedidoitens` (
  `idPedidoitens` INT NOT NULL,
  `qtdade` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  PRIMARY KEY (`idPedidoitens`),
  -- INDEX `fk_Pedidoitens_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  -- INDEX `fk_Pedidoitens_Pedidos1_idx` (`Pedidos_idPedidos` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidoitens_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidoitens_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `mydb`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
